FROM debian

#RUN apt-get update -y && apt-get install apt-utils python3-pip -y \
RUN  apt-get install wget -y \
&& apt-get clean

RUN pip3 install --upgrade pip setuptools wheel

# Python setup
RUN cd /opt && wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz \
&& tar xzf Python-3.8.2.tgz && cd Python-3.8.2 \
&& ./configure --enable-optimizations \
&& make altinstall