FROM jenkins/jenkins:lts

EXPOSE 9090

ARG WORKDIR=/home/jenkins

WORKDIR = $WORKDIR

VOLUME /project
VOLUME /test_results

USER root
RUN apt-get update && apt-get install apt-utils vim mc -y

USER jenkins
